### PR TITLE
Feature / Check if phone is busy 

### PR DESCRIPTION
**Pull request by aarkalyk**
Method for checking if there are any active calls on the device. 
Pretty convenient to use with the `async/await` syntax. 
```
async () => {
   const isBusy = await RNCallKit.checkIfBusy();
   if (isBusy) {
      // handle accordingly 
   }
}
```

### CODE REVIEW

**Comment by aarkalyk** [comment]
Hey, @ianlin ! Can you, please, review this one?

**Comment by ianlin** [comment]
Hi @aarkalyk can you please have a look on my review? Cheers.

**Comment by aarkalyk** [comment]
Hey, @ianlin ! Thanks for the feedback! Can you please take one more look at the PR?:)

**Comment by ianlin** [comment]
Thanks!

**Pull request merged**
